# Generated by Django 5.1.6 on 2025-03-06 10:29

import django.db.models.deletion
import tasks.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("Task_ID", models.AutoField(primary_key=True, serialize=False)),
                (
                    "Status",
                    models.CharField(
                        choices=[
                            ("NS", "Not started"),
                            ("ACT", "Active"),
                            ("DN", "Done"),
                        ],
                        default="NS",
                        max_length=15,
                    ),
                ),
                ("Description", models.TextField()),
                (
                    "Priority",
                    models.CharField(
                        choices=[("H", "High"), ("M", "Medium"), ("L", "Low")],
                        default="H",
                        max_length=1,
                    ),
                ),
                (
                    "Deadline",
                    models.DateField(default=tasks.models.Task.default_deadline),
                ),
                (
                    "User_ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
